server:
  port: 8789
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-sellergoods-ms'
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC'
    type: com.alibaba.druid.pool.DruidDataSource

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
#    pool:
#      enabled: true
#      max-connections: 50
#      expiry-timeout: 10000
#      idle-timeout: 30000
mybatis:
  type-aliases-package: com.lt.pojo
  mapper-locations: 'classpath*:com/**/*Mapper.xml'

pagehelper:
  helper-dialect: mysql
  reasonable: true

 