eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-shopping-goods:
      path: /shopping-goods/**
      service-id: shopping-goods-ms
    api-shoppring-content:
      path: /shopping-content/**
      service-id: shopping-content-ms
    api-shoppring-search:
      path: /shopping-search/**
      service-id: shopping-search-ms
    api-shoppring-sellergoods:
      path: /shopping-sellergoods/**
      service-id: shopping-sellergoods-ms
